server:
  port: 3300
spring:
  application:
    name: product_server
spring:
   datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///aigou_product
    driver-class-name: com.mysql.jdbc.Driver
