server:
  port: 2001
spring:
  application:
    name: zuul
zuul:
  ignoredServices: '*'
  routes:
    plat:
      path: /plat/** #平台服务的请求路径
      serviceId: plat-server
    product:
      path: /product/**
      serviceId: product-server
    common:
      path: /common/**
      serviceId: common-server
  prefix: /services #请求前缀
